// Pure, framework-free helpers for the ContentUnit detail screen. Kept dependency-free so they are
// cheap to unit test in isolation from React, Next.js, and the live API.
import type {
  Comment,
  ContentUnitVariant,
  ContentUnitVersion,
  ContentUnitWhereUsedReference,
  Note,
  Taxonomy
} from "@/lib/api";

export type Tone = "ok" | "warn" | "danger" | "ai" | "primary" | "neutral";
export type ScoreTone = "good" | "mid" | "low";

/** Normalizes a score that may arrive as a 0-1 fraction or a 0-100 integer. Returns null when the
 * field was not returned by the API at all, so callers can render an honest "not available" state
 * instead of a fabricated number. */
export function normalizeScore(value: number | null | undefined): number | null {
  if (typeof value !== "number" || Number.isNaN(value)) return null;
  const normalized = value <= 1 ? value * 100 : value;
  return Math.max(0, Math.min(100, Math.round(normalized)));
}

export function scoreTone(score: number, thresholds: { good: number; mid: number } = { good: 85, mid: 70 }): ScoreTone {
  if (score >= thresholds.good) return "good";
  if (score >= thresholds.mid) return "mid";
  return "low";
}

/** Descriptive label derived from the real score value itself (not a separate fabricated field). */
export function scoreDescriptor(score: number, kind: "quality" | "usage" | "relevance"): string {
  const tone = scoreTone(score, { good: 90, mid: 80 });
  const labels: Record<"quality" | "usage" | "relevance", Record<ScoreTone, string>> = {
    quality: { good: "Excellent", mid: "Good", low: "Needs review" },
    usage: { good: "High", mid: "Moderate", low: "Low" },
    relevance: { good: "Highly relevant", mid: "Relevant", low: "Loosely relevant" }
  };
  return labels[kind][tone];
}

export function formatDate(value?: string | null): string {
  if (!value) return "Unknown date";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return "Unknown date";
  return parsed.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

export function formatDateTime(value?: string | null): string {
  if (!value) return "Unknown date";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return "Unknown date";
  return parsed.toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
}

export function approvalTone(value: string): Tone {
  if (value === "approved") return "ok";
  if (value === "deprecated" || value === "archived") return "danger";
  if (value === "review") return "warn";
  return "neutral";
}

export function freshnessTone(value: string): Tone {
  if (value === "fresh") return "ok";
  if (value === "stale") return "danger";
  return "warn";
}

export type VersionBadge = { label: string; tone: Tone };

/** Derives a single "state" badge for a version rail card / carousel card from real, already-loaded
 * fields only (variant.isCanonical, version.approvalState, variant.linkedBy). There is no per-version
 * "generated by AI" flag in the API, so AI/manual linkage is inferred from the owning variant. */
export function versionBadge(variant: ContentUnitVariant | undefined, version: ContentUnitVersion): VersionBadge {
  if (variant?.isCanonical) return { label: "Canonical", tone: "primary" };
  if (version.approvalState === "approved") return { label: "Approved", tone: "ok" };
  if (variant?.linkedBy === "ai") return { label: "AI-linked", tone: "ai" };
  if (variant?.linkedBy === "hybrid") return { label: "Hybrid-linked", tone: "ai" };
  if (variant?.linkedBy === "manual") return { label: "Manual-linked", tone: "neutral" };
  return { label: titleCase(version.approvalState), tone: approvalTone(version.approvalState) };
}

export function taxonomyTags(taxonomy?: Taxonomy): string[] {
  if (!taxonomy) return [];
  const values = Object.values(taxonomy)
    .flatMap((value) => (Array.isArray(value) ? value : []))
    .filter((value): value is string => typeof value === "string" && value.trim().length > 0);
  return Array.from(new Set(values));
}

export function titleCase(value: string): string {
  return value
    .replaceAll("_", " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

export type WhereUsedKind = { label: string; color: string };

/** Maps a where-used objectType to a real, honest label + color. No dates or parent titles are
 * fabricated here -- callers should render only the fields the API actually returned. */
export function whereUsedKind(objectType: string): WhereUsedKind {
  const normalized = objectType?.toLowerCase();
  if (normalized === "work_product_version" || normalized === "work_product") return { label: "Work Product", color: "var(--primary)" };
  if (normalized === "content_block_version" || normalized === "content_block") return { label: "Content Block", color: "var(--ai)" };
  if (normalized === "storyboard" || normalized === "storyboard_snapshot") return { label: "Storyboard", color: "var(--ok)" };
  if (normalized === "play") return { label: "Play", color: "var(--warn)" };
  return { label: titleCase(objectType ?? "Reference"), color: "var(--ink-3)" };
}

export function sortVersionsByDateDesc<T extends { createdAt?: string }>(versions: T[]): T[] {
  return [...versions].sort((left, right) => dateValue(right.createdAt) - dateValue(left.createdAt));
}

function dateValue(value?: string) {
  if (!value) return 0;
  const parsed = Date.parse(value);
  return Number.isNaN(parsed) ? 0 : parsed;
}

export type FlatVersion = { variant: ContentUnitVariant; version: ContentUnitVersion };

export function flattenVersionGroups(groups: Array<{ variant: ContentUnitVariant; versions: ContentUnitVersion[] }>): FlatVersion[] {
  const flat = groups.flatMap((group) => group.versions.map((version) => ({ variant: group.variant, version })));
  return [...flat].sort((left, right) => dateValue(right.version.createdAt) - dateValue(left.version.createdAt));
}

export type LinkSourceCounts = { canonical: number; manual: number; ai: number; hybrid: number; total: number };

export function countVariantsByLinkSource(variants: ContentUnitVariant[]): LinkSourceCounts {
  return variants.reduce<LinkSourceCounts>(
    (totals, variant) => {
      totals.total += 1;
      if (variant.isCanonical) totals.canonical += 1;
      else if (variant.linkedBy === "ai") totals.ai += 1;
      else if (variant.linkedBy === "hybrid") totals.hybrid += 1;
      else totals.manual += 1;
      return totals;
    },
    { canonical: 0, manual: 0, ai: 0, hybrid: 0, total: 0 }
  );
}

export type SlidePosition = { index: number; total: number };

/** Derives "slide N of M" from the *real* position of a version inside its primary parent
 * WorkProduct's filmstrip (rather than the unused/null sourceOrderIndex field). Returns null when
 * the version is not present in the filmstrip so callers can omit the line entirely. */
export function findFilmstripPosition(filmstrip: ContentUnitVersion[] | undefined, versionId: string): SlidePosition | null {
  if (!filmstrip || filmstrip.length === 0) return null;
  const index = filmstrip.findIndex((entry) => entry.id === versionId);
  if (index === -1) return null;
  return { index: index + 1, total: filmstrip.length };
}

export function primaryParentReference(whereUsed: ContentUnitWhereUsedReference[]): ContentUnitWhereUsedReference | undefined {
  return (
    whereUsed.find((item) => item.objectType?.toLowerCase() === "work_product_version") ??
    whereUsed.find((item) => item.objectType?.toLowerCase() === "content_block_version") ??
    whereUsed[0]
  );
}

export type ActivityEvent = {
  id: string;
  date: string;
  kind: "version" | "comment" | "note";
  title: string;
  description?: string;
  tone: Tone;
};

/** Builds an honest activity timeline from data already loaded on this page (version creation,
 * comments, notes). This is NOT the governed audit-event log -- that endpoint is admin-gated and is
 * intentionally not called from this screen (see audit-digest.md API NEEDS). */
export function buildActivityTimeline({
  versions,
  comments,
  notes
}: {
  versions: Array<{ variant?: ContentUnitVariant; version: ContentUnitVersion }>;
  comments: Comment[];
  notes: Note[];
}): ActivityEvent[] {
  const versionEvents: ActivityEvent[] = versions
    .filter((entry) => entry.version.createdAt)
    .map((entry) => ({
      id: `version-${entry.version.id}`,
      date: entry.version.createdAt as string,
      kind: "version",
      title: `Version ${entry.version.versionNumber} created`,
      description: `${entry.variant ? `${titleCase(entry.variant.variantLabel)} variant` : "Standalone version"} · ${titleCase(entry.version.approvalState)}`,
      tone: approvalTone(entry.version.approvalState)
    }));

  const commentEvents: ActivityEvent[] = comments
    .filter((comment) => comment.createdAt)
    .map((comment) => ({
      id: `comment-${comment.id}`,
      date: comment.createdAt as string,
      kind: "comment",
      title: comment.parentCommentId ? "Reply added" : "Comment added",
      description: truncate(comment.body, 96),
      tone: "primary"
    }));

  const noteEvents: ActivityEvent[] = notes
    .filter((note) => note.createdAt)
    .map((note) => ({
      id: `note-${note.id}`,
      date: note.createdAt as string,
      kind: "note",
      title: note.title ? `Note added: ${note.title}` : "Note added",
      description: truncate(note.body, 96),
      tone: "warn"
    }));

  return [...versionEvents, ...commentEvents, ...noteEvents].sort((left, right) => dateValue(right.date) - dateValue(left.date));
}

function truncate(value: string, max: number) {
  return value.length > max ? `${value.slice(0, max - 1)}…` : value;
}

export function groupCommentsIntoThreads(comments: Comment[]): Array<{ root: Comment; replies: Comment[] }> {
  const roots = comments.filter((comment) => !comment.parentCommentId);
  const byParent = new Map<string, Comment[]>();
  for (const comment of comments) {
    if (!comment.parentCommentId) continue;
    const list = byParent.get(comment.parentCommentId) ?? [];
    list.push(comment);
    byParent.set(comment.parentCommentId, list);
  }
  return roots.map((root) => ({ root, replies: sortVersionsByDateDesc(byParent.get(root.id) ?? []).reverse() }));
}
