/* MySelection — global "shopping cart" for items across the app.
   - Collapsed: small drawer pill in the topbar with item count badge
   - Expanded: full right sidebar showing selected items grouped by entity type
   - Only shows sections that have items
*/

function MySelectionProvider({children}) {
  // Seed with a realistic set of mixed-type items so users can see the pattern.
  const [items, setItems] = React.useState(() => {
    try {
      const s = localStorage.getItem("bbv2_selection");
      if (s) return JSON.parse(s);
    } catch(e){}
    return [
      {id:"wp-1", type:"workproduct", title:"Financial Services Pitch Deck", meta:"Slides · May 7, 2024", badges:["Approved","Fresh"], v:"v3"},
      {id:"wp-2", type:"workproduct", title:"Northwind Bank — RFP Response", meta:"Word Doc · May 9, 2024", badges:["Approved","Fresh"], v:"v2"},
      {id:"wp-3", type:"workproduct", title:"AI Insights Framework (Financial Services)", meta:"Whitepaper · Apr 30, 2024", badges:["Approved","Canonical"], v:"v1"},
      {id:"cu-1", type:"contentunit", title:"Executive Summary — AI Platform", meta:"Slide · v2.3 · 92% match", badges:["Reused often"], v:"v2.3"},
      {id:"cu-2", type:"contentunit", title:"ROI Comparison Chart", meta:"Chart · v1.4 · 88% match", badges:["Fresh"], v:"v1.4"},
      {id:"play-1", type:"play", title:"Global Expansion Play", meta:"Playbook · Used 9× · 58% win rate", badges:["Best Match"]},
      {id:"slide-1", type:"slide", title:"Business Impact — Quantified Outcomes", meta:"Slide · SLD-10540 · v2.1", badges:["High relevance"]},
      {id:"gen-1", type:"generated", title:"Financial Services Executive Summary", meta:"Generated · Just now", badges:["Generated"]},
    ];
  });
  const [open, setOpen] = React.useState(false);

  React.useEffect(()=>{
    try { localStorage.setItem("bbv2_selection", JSON.stringify(items)); } catch(e){}
  },[items]);

  const api = React.useMemo(() => ({
    items, setItems, open, setOpen,
    add: (it)=>setItems(p=>p.find(x=>x.id===it.id)?p:[...p,it]),
    remove: (id)=>setItems(p=>p.filter(x=>x.id!==id)),
    clear: ()=>setItems([]),
    count: items.length,
  }), [items, open]);

  return (
    <MySelectionCtx.Provider value={api}>
      {children}
      <MySelectionSidebar/>
    </MySelectionCtx.Provider>
  );
}

const MySelectionCtx = React.createContext(null);
const useMySelection = () => React.useContext(MySelectionCtx);

function MySelectionButton() {
  const sel = useMySelection();
  if (!sel) return null;
  return (
    <button
      onClick={()=>sel.setOpen(true)}
      title="My selection"
      className="icon-btn borderless"
      style={{
        position:"relative",
        display:"flex",alignItems:"center",gap:6,
        padding:"5px 10px",width:"auto",
        borderRadius:999,
        background:sel.count>0?"var(--primary-bg)":"transparent",
        color:sel.count>0?"var(--primary)":"var(--ink-2)",
        border:sel.count>0?"1px solid var(--primary-border)":"1px solid transparent",
        fontSize:12,fontWeight:600
      }}
    >
      <Ico.Bookmark size={13}/>
      <span>Selection</span>
      {sel.count>0 && (
        <span style={{
          background:"var(--primary)",color:"#fff",
          fontSize:10,fontWeight:700,
          minWidth:18,height:18,padding:"0 5px",
          borderRadius:9,display:"inline-flex",alignItems:"center",justifyContent:"center"
        }}>{sel.count}</span>
      )}
    </button>
  );
}

/* Group metadata — order + icon + label + colors */
const SEL_GROUPS = [
  {k:"workproduct", l:"Work Products", ico:"FileText", color:"var(--primary)"},
  {k:"play",         l:"Plays",        ico:"Plays",    color:"var(--primary)"},
  {k:"contentunit",  l:"Content Units", ico:"Deck",    color:"var(--primary)"},
  {k:"slide",        l:"Slides",       ico:"Deck",     color:"var(--primary)"},
  {k:"opportunity",  l:"Opportunities",ico:"Target",   color:"var(--primary)"},
  {k:"asset",        l:"Assets",       ico:"Image",    color:"var(--primary)"},
  {k:"generated",    l:"Generated by BoxBrain", ico:"Sparkle", color:"var(--ai)"},
];

function MySelItemRow({it, onRemove}) {
  const thumbVariant = it.type==="workproduct" ? "dark"
                     : it.type==="contentunit" ? "light"
                     : it.type==="slide"       ? "dark"
                     : it.type==="generated"   ? "teal"
                     : "light";
  const showThumb = ["workproduct","contentunit","slide","generated"].includes(it.type);

  return (
    <div style={{
      display:"grid",gridTemplateColumns:showThumb?"60px 1fr 20px":"1fr 20px",
      gap:10,padding:"10px 12px",alignItems:"flex-start",
      borderBottom:"1px solid var(--line-soft)"
    }}>
      {showThumb && (
        <div style={{width:60,height:40,borderRadius:4,overflow:"hidden",flexShrink:0,border:"1px solid var(--line-soft)"}}>
          <SlideThumb variant={thumbVariant} title={it.title.split(" ").slice(0,2).join(" ")} brand=""/>
        </div>
      )}
      <div style={{minWidth:0}}>
        <div style={{fontSize:12,fontWeight:600,color:"var(--ink)",lineHeight:1.3,
                     overflow:"hidden",display:"-webkit-box",
                     WebkitLineClamp:2,WebkitBoxOrient:"vertical"}}>
          {it.title}
        </div>
        <div className="muted" style={{fontSize:10,marginTop:3}}>{it.meta}</div>
        {it.badges && it.badges.length>0 && (
          <div className="flex items-center gap-1" style={{marginTop:4,flexWrap:"wrap"}}>
            {it.badges.map((b,i)=>{
              const kind = b==="Approved" ? "ok"
                         : b==="Fresh" ? "ok"
                         : b==="Canonical" ? "primary"
                         : b==="Generated" ? "ai"
                         : "";
              const bg = kind==="ok" ? "#ecfdf5" : kind==="primary" ? "var(--primary-bg)" : kind==="ai" ? "var(--ai-bg)" : "var(--bg-2)";
              const fg = kind==="ok" ? "var(--ok)" : kind==="primary" ? "var(--primary)" : kind==="ai" ? "var(--ai)" : "var(--ink-3)";
              return <span key={i} style={{fontSize:9,fontWeight:600,padding:"1px 6px",borderRadius:3,background:bg,color:fg}}>{b}</span>;
            })}
          </div>
        )}
      </div>
      <button className="icon-btn borderless" style={{width:20,height:20,alignSelf:"flex-start"}} onClick={onRemove}>
        <Ico.X size={11}/>
      </button>
    </div>
  );
}

function MySelectionSidebar() {
  const sel = useMySelection();
  const [collapsedGroups, setCollapsedGroups] = React.useState({});
  if (!sel) return null;

  // Group by type, preserving group order
  const grouped = SEL_GROUPS.map(g => ({
    ...g,
    items: sel.items.filter(it => it.type === g.k)
  })).filter(g => g.items.length>0);

  return (
    <>
      {/* Backdrop */}
      {sel.open && (
        <div
          onClick={()=>sel.setOpen(false)}
          style={{
            position:"fixed",inset:0,background:"rgba(15,23,42,0.18)",zIndex:58,
            opacity:sel.open?1:0,transition:"opacity .15s"
          }}
        />
      )}

      {/* Sidebar panel */}
      <aside style={{
        position:"fixed",top:0,right:0,bottom:0,
        width:340,
        background:"var(--paper)",
        borderLeft:"1px solid var(--line)",
        boxShadow:"-12px 0 40px rgba(15,23,42,0.08)",
        transform:sel.open?"translateX(0)":"translateX(100%)",
        transition:"transform .18s ease-out",
        zIndex:60,
        display:"flex",flexDirection:"column"
      }}>
        {/* Header */}
        <div style={{
          padding:"14px 16px",
          borderBottom:"1px solid var(--line)",
          display:"flex",alignItems:"center",justifyContent:"space-between"
        }}>
          <div className="flex items-center gap-2">
            <b style={{fontSize:14}}>My selection</b>
            <span style={{
              background:"var(--bg-2)",color:"var(--ink-3)",
              fontSize:11,fontWeight:700,padding:"1px 7px",borderRadius:9
            }}>{sel.count}</span>
          </div>
          <div className="flex items-center gap-1">
            <button className="icon-btn borderless" title="Close" onClick={()=>sel.setOpen(false)} style={{width:26,height:26}}>
              <Ico.X size={13}/>
            </button>
          </div>
        </div>

        {/* Scrollable content */}
        <div style={{flex:1,overflow:"auto"}}>
          {grouped.length===0 ? (
            <div style={{padding:"40px 20px",textAlign:"center",color:"var(--ink-3)"}}>
              <Ico.Bookmark size={24} color="var(--ink-4)"/>
              <div style={{fontSize:13,fontWeight:600,marginTop:10,color:"var(--ink-2)"}}>No items selected yet</div>
              <div style={{fontSize:11,marginTop:4,lineHeight:1.5}}>
                Items you save from Ask BoxBrain, Library, Work Products,<br/>
                and elsewhere will appear here.
              </div>
            </div>
          ) : grouped.map(g => {
            const Icon = Ico[g.ico] || Ico.FileText;
            const collapsed = collapsedGroups[g.k];
            return (
              <div key={g.k}>
                {/* Section header */}
                <div
                  onClick={()=>setCollapsedGroups(p=>({...p,[g.k]:!p[g.k]}))}
                  style={{
                    padding:"10px 14px 8px",
                    display:"flex",alignItems:"center",gap:6,
                    cursor:"pointer",
                    background:"var(--bg)",
                    borderBottom:"1px solid var(--line-soft)",
                    position:"sticky",top:0,zIndex:2
                  }}
                >
                  <Icon size={11} color={g.color}/>
                  <span style={{fontSize:10,fontWeight:700,letterSpacing:"0.05em",textTransform:"uppercase",color:"var(--ink-2)",flex:1}}>
                    {g.l}
                  </span>
                  <span style={{fontSize:10,color:"var(--ink-3)",fontWeight:600}}>{g.items.length}</span>
                  <Ico.Down size={10} color="var(--ink-3)" style={{transform:collapsed?"rotate(-90deg)":"none",transition:"transform .15s"}}/>
                </div>
                {!collapsed && g.items.map(it => (
                  <MySelItemRow key={it.id} it={it} onRemove={()=>sel.remove(it.id)}/>
                ))}
              </div>
            );
          })}

          {/* Add custom content */}
          {grouped.length>0 && (
            <div style={{padding:"10px 14px",textAlign:"center"}}>
              <a className="link flex items-center gap-1" style={{fontSize:11,justifyContent:"center",fontWeight:600}}>
                <Ico.Plus size={11}/> Add custom content
              </a>
            </div>
          )}
        </div>

        {/* Quick actions */}
        {grouped.length>0 && (
          <div style={{borderTop:"1px solid var(--line)",padding:"12px 14px"}}>
            <div style={{fontSize:10,fontWeight:700,letterSpacing:"0.05em",textTransform:"uppercase",color:"var(--ink-3)",marginBottom:8}}>
              Quick Actions
            </div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:8}}>
              <button className="btn btn-sm" style={{justifyContent:"flex-start"}}><Ico.Compare size={11}/> Compare</button>
              <button className="btn btn-sm" style={{justifyContent:"flex-start"}}><Ico.FileText size={11}/> Create brief</button>
              <button className="btn btn-sm" style={{justifyContent:"flex-start"}}><Ico.Download size={11}/> Export to PPT</button>
              <button className="btn btn-sm" style={{justifyContent:"flex-start"}}><Ico.Share size={11}/> Share collection</button>
            </div>
            <button className="btn btn-primary btn-sm" style={{width:"100%"}}>
              <Ico.Sparkle size={12}/> Start a new chat
            </button>
            <div className="muted" style={{fontSize:10,textAlign:"center",marginTop:8}}>
              Selections are saved to this session
            </div>
          </div>
        )}
      </aside>
    </>
  );
}

window.MySelectionProvider = MySelectionProvider;
window.MySelectionButton = MySelectionButton;
window.MySelectionSidebar = MySelectionSidebar;
window.MySelectionCtx = MySelectionCtx;
