"use client";

import clsx from "clsx";
import {
  Bookmark,
  ChevronDown,
  Download,
  FileText,
  GitCompare,
  Image as ImageIcon,
  Layers,
  MessageSquarePlus,
  Presentation,
  Route,
  Share2,
  Sparkles,
  Target,
  X,
  type LucideIcon
} from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { SlideThumb } from "@/components/ui";
import { useMySelection } from "./context";
import type { SelectionItem, SelectionItemType } from "./types";

const FOCUSABLE_SELECTOR = 'a[href], button:not([disabled]), textarea, input, select, [tabindex]:not([tabindex="-1"])';

const THUMB_TYPES: SelectionItemType[] = ["workproduct", "contentunit", "slide", "generated"];

type GroupConfig = {
  type: SelectionItemType;
  label: string;
  icon: LucideIcon;
  color?: string;
};

const GROUPS: GroupConfig[] = [
  { type: "workproduct", label: "Work Products", icon: FileText },
  { type: "play", label: "Plays", icon: Route },
  { type: "contentunit", label: "Content Units", icon: Layers },
  { type: "slide", label: "Slides", icon: Presentation },
  { type: "opportunity", label: "Opportunities", icon: Target },
  { type: "asset", label: "Assets", icon: ImageIcon },
  { type: "generated", label: "Generated by BoxBrain", icon: Sparkles, color: "var(--ai)" }
];

function thumbVariantFor(type: SelectionItemType): "dark" | "light" | "teal" | "purple" {
  if (type === "workproduct" || type === "slide") return "dark";
  if (type === "generated") return "teal";
  return "light";
}

export function MySelectionDrawer() {
  const { items, isOpen, close, remove } = useMySelection();
  const panelRef = useRef<HTMLDivElement>(null);
  const previouslyFocused = useRef<HTMLElement | null>(null);
  const [collapsedGroups, setCollapsedGroups] = useState<Record<string, boolean>>({});
  const [entered, setEntered] = useState(false);

  const grouped = useMemo(
    () =>
      GROUPS.map((group) => ({
        ...group,
        items: items.filter((item) => item.type === group.type)
      })).filter((group) => group.items.length > 0),
    [items]
  );

  // Capture the trigger element and move focus into the panel when the drawer opens; restore focus
  // to the trigger when it closes so keyboard/screen-reader users aren't dropped back at <body>.
  useEffect(() => {
    if (!isOpen) {
      setEntered(false);
      return;
    }
    previouslyFocused.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const raf = requestAnimationFrame(() => setEntered(true));
    const focusTarget = panelRef.current?.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
    focusTarget?.focus();
    return () => {
      cancelAnimationFrame(raf);
      previouslyFocused.current?.focus?.();
    };
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;

    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        event.preventDefault();
        close();
        return;
      }
      if (event.key !== "Tab") return;
      const panel = panelRef.current;
      if (!panel) return;
      const focusable = Array.from(panel.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR));
      if (focusable.length === 0) return;
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, close]);

  if (!isOpen) return null;

  const compareEligible = items.length === 2 && items[0].type === items[1].type;
  const compareHint = compareEligible ? "Compare the two selected items" : "Select exactly two items of the same type to compare";

  return (
    <>
      <div className="fixed inset-0 z-[58] bg-slate-900/20" onClick={close} aria-hidden="true" />
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="my-selection-heading"
        data-testid="my-selection-drawer"
        className={clsx(
          "fixed inset-y-0 right-0 z-[60] flex w-[340px] max-w-[92vw] flex-col border-l border-[var(--line)] bg-[var(--paper)] shadow-[var(--shadow-lg)] transition-transform duration-200 ease-out",
          entered ? "translate-x-0" : "translate-x-full"
        )}
      >
        <div className="flex items-center justify-between border-b border-[var(--line)] px-4 py-3.5">
          <div className="flex items-center gap-2">
            <b id="my-selection-heading" className="text-sm font-bold text-[var(--ink)]">
              My selection
            </b>
            <span className="rounded-full bg-[var(--bg-2)] px-[7px] py-px text-[11px] font-bold text-[var(--ink-3)]">{items.length}</span>
          </div>
          <button type="button" className="icon-btn borderless h-[26px] w-[26px]" title="Close" aria-label="Close my selection" onClick={close}>
            <X size={13} />
          </button>
        </div>

        <div className="flex-1 overflow-auto">
          {grouped.length === 0 ? (
            <div className="px-5 py-10 text-center text-[var(--ink-3)]">
              <Bookmark size={24} className="mx-auto text-[var(--ink-4)]" />
              <div className="mt-2.5 text-[13px] font-semibold text-[var(--ink-2)]">No items selected yet</div>
              <p className="mt-1 text-[11px] leading-relaxed">
                Items you save from Ask BoxBrain, Library, Work Products, and elsewhere will appear here.
              </p>
            </div>
          ) : (
            grouped.map((group) => {
              const Icon = group.icon;
              const collapsed = Boolean(collapsedGroups[group.type]);
              return (
                <div key={group.type}>
                  <button
                    type="button"
                    onClick={() => setCollapsedGroups((prev) => ({ ...prev, [group.type]: !prev[group.type] }))}
                    aria-expanded={!collapsed}
                    className="sticky top-0 z-[2] flex w-full items-center gap-1.5 border-b border-[var(--line-soft)] bg-[var(--bg)] px-3.5 py-2 text-left"
                  >
                    <Icon size={11} style={{ color: group.color ?? "var(--primary)" }} />
                    <span className="flex-1 text-[10px] font-bold uppercase tracking-[0.05em] text-[var(--ink-2)]">{group.label}</span>
                    <span className="text-[10px] font-semibold text-[var(--ink-3)]">{group.items.length}</span>
                    <ChevronDown size={10} className={clsx("text-[var(--ink-3)] transition-transform", collapsed && "-rotate-90")} />
                  </button>
                  {!collapsed && group.items.map((item) => <SelectionRow key={item.id} item={item} onRemove={() => remove(item.id)} />)}
                </div>
              );
            })
          )}
        </div>

        {grouped.length > 0 && (
          <div className="border-t border-[var(--line)] px-3.5 py-3">
            <div className="mb-2 text-[10px] font-bold uppercase tracking-[0.05em] text-[var(--ink-3)]">Quick Actions</div>
            <div className="mb-2 grid grid-cols-2 gap-1.5">
              <button type="button" className="btn btn-sm justify-start" disabled={!compareEligible} title={compareHint}>
                <GitCompare size={11} /> Compare
              </button>
              <button type="button" className="btn btn-sm justify-start" disabled title="Coming soon">
                <FileText size={11} /> Create brief
              </button>
              <button type="button" className="btn btn-sm justify-start" disabled title="Coming soon">
                <Download size={11} /> Export to PPT
              </button>
              <button type="button" className="btn btn-sm justify-start" disabled title="Coming soon">
                <Share2 size={11} /> Share collection
              </button>
            </div>
            <button type="button" className="btn btn-primary btn-sm w-full" disabled title="Coming soon">
              <MessageSquarePlus size={12} /> Start a chat
            </button>
            <div className="muted mt-2 text-center text-[10px]">Selections are saved to this browser</div>
          </div>
        )}
      </div>
    </>
  );
}

function SelectionRow({ item, onRemove }: { item: SelectionItem; onRemove: () => void }) {
  const showThumb = THUMB_TYPES.includes(item.type);
  return (
    <div
      className={clsx("grid items-start gap-2.5 border-b border-[var(--line-soft)] px-3.5 py-2.5 last:border-b-0", showThumb ? "grid-cols-[60px_1fr_20px]" : "grid-cols-[1fr_20px]")}
    >
      {showThumb && (
        <div className="h-10 w-[60px] shrink-0 overflow-hidden rounded border border-[var(--line-soft)]">
          {item.thumb ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={item.thumb} alt="" className="h-full w-full object-cover" />
          ) : (
            <SlideThumb title={item.title.split(" ").slice(0, 2).join(" ")} brand="" variant={thumbVariantFor(item.type)} chart={false} className="h-full w-full" />
          )}
        </div>
      )}
      <div className="min-w-0">
        <div className="line-clamp-2 text-xs font-semibold leading-tight text-[var(--ink)]">{item.title}</div>
        {item.subtitle && <div className="muted mt-0.5 text-[10px]">{item.subtitle}</div>}
      </div>
      <button type="button" className="icon-btn borderless h-5 w-5 self-start" aria-label={`Remove ${item.title} from my selection`} onClick={onRemove}>
        <X size={11} />
      </button>
    </div>
  );
}
