"use client";

import { ChevronDown, ChevronUp, Download, FileText, GitCompare, Plus, Share2, Sparkles, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Card, SlideThumb } from "@/components/ui";
import { useMySelection, type SelectionItem } from "@/components/selection";

/** Persistent "My selection" rail for the Ask screen (design: routes_1.jsx RouteAskBoxBrain, right
 * column). Backed by the shared cross-app My Selection store (`@/components/selection`) so items
 * added here also show up in the global topbar drawer, and vice versa — there is exactly one
 * session-scoped selection, not a bespoke Ask-only copy of it. Quick Actions that have no backend
 * support (Create brief / Export to PPT / Share collection) are rendered disabled with an honest
 * "coming soon" tooltip rather than faked; see audit-digest ask-search API[no] gap. */
export function AskSelectionRail({ onStartNewChat }: { onStartNewChat: () => void }) {
  const { items, remove, add } = useMySelection();
  const [collapsed, setCollapsed] = useState(false);
  const [addingCustom, setAddingCustom] = useState(false);
  const [customTitle, setCustomTitle] = useState("");

  const savedItems = items.filter((item) => item.type !== "generated");
  const generatedItems = items.filter((item) => item.type === "generated");
  const compareEligible = items.length === 2 && items[0].type === items[1].type;
  const compareHint = compareEligible ? "Compare the two selected items" : "Select exactly two items of the same type to compare";

  function submitCustomItem(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const title = customTitle.trim();
    if (!title) return;
    const item: SelectionItem = {
      id: `custom-${Date.now()}-${Math.round(Math.random() * 1000)}`,
      type: "asset",
      title,
      subtitle: "Custom · added manually"
    };
    add(item);
    setCustomTitle("");
    setAddingCustom(false);
  }

  return (
    <Card className="sticky top-4 flex flex-col p-0" data-testid="ask-selection-rail">
      <div className="flex items-center gap-2 border-b border-[var(--line)] px-4 py-3">
        <b className="text-sm">My selection</b>
        <span className="count-inline">{items.length}</span>
        <span className="flex-1" />
        <button
          type="button"
          className="icon-btn borderless"
          aria-expanded={!collapsed}
          aria-label={collapsed ? "Expand my selection" : "Collapse my selection"}
          onClick={() => setCollapsed((value) => !value)}
        >
          {collapsed ? <ChevronDown size={14} /> : <ChevronUp size={14} />}
        </button>
      </div>

      {!collapsed && (
        <div className="max-h-[70vh] overflow-y-auto">
          <div className="px-4 pt-3">
            {items.length === 0 ? (
              <div className="rounded-lg border border-dashed border-slate-200 p-3 text-sm text-slate-500">
                Nothing saved yet. Use the <Plus size={12} className="inline" aria-hidden="true" /> control on any result card to add it here.
              </div>
            ) : (
              <div className="palette-group-label px-0">Saved items</div>
            )}
          </div>

          <div className="px-4">
            {savedItems.map((item) => (
              <SelectionRow key={item.id} item={item} onRemove={() => remove(item.id)} />
            ))}
          </div>

          {items.length > 0 && (
            <div className="px-4">
              <div className="palette-group-label mt-3 px-0">Generated by BoxBrain</div>
              {generatedItems.length === 0 ? (
                <p className="muted text-xs">BoxBrain hasn&apos;t generated any artifacts for this session yet.</p>
              ) : (
                generatedItems.map((item) => <SelectionRow key={item.id} item={item} onRemove={() => remove(item.id)} />)
              )}
            </div>
          )}

          <div className="px-4 pb-4">
            {addingCustom ? (
              <form onSubmit={submitCustomItem} className="mt-3 grid gap-2">
                <input
                  autoFocus
                  className="input"
                  placeholder="Custom item title"
                  value={customTitle}
                  onChange={(event) => setCustomTitle(event.target.value)}
                  aria-label="Custom selection item title"
                />
                <div className="flex gap-2">
                  <button type="submit" className="btn btn-primary btn-sm flex-1">
                    Add
                  </button>
                  <button type="button" className="btn btn-sm" onClick={() => setAddingCustom(false)}>
                    Cancel
                  </button>
                </div>
              </form>
            ) : (
              <button type="button" className="btn btn-ghost btn-sm mt-3 w-full" onClick={() => setAddingCustom(true)}>
                <Plus size={12} /> Add custom content
              </button>
            )}

            <div className="palette-group-label mt-4 px-0">Quick actions</div>
            <div className="grid grid-cols-2 gap-2">
              <button type="button" className="btn btn-sm justify-start" disabled={!compareEligible} title={compareHint}>
                <GitCompare size={12} /> Compare
              </button>
              <button type="button" className="btn btn-sm justify-start" disabled title="Not available yet — no backend support">
                <FileText size={12} /> Create brief
              </button>
              <button type="button" className="btn btn-sm justify-start" disabled title="Not available yet — no backend support">
                <Download size={12} /> Export to PPT
              </button>
              <button type="button" className="btn btn-sm justify-start" disabled title="Not available yet — no backend support">
                <Share2 size={12} /> Share collection
              </button>
            </div>

            <button type="button" className="btn btn-primary mt-3 w-full" onClick={onStartNewChat}>
              <Sparkles size={14} /> Start a new chat
            </button>
            <div className="muted mt-2 text-center text-[11px]">Selections are saved to this browser</div>
          </div>
        </div>
      )}
    </Card>
  );
}

function SelectionRow({ item, onRemove }: { item: SelectionItem; onRemove: () => void }) {
  return (
    <div className="tray-item">
      <div className="tray-item-thumb">
        {item.thumb ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={item.thumb} alt="" className="h-full w-full object-cover" />
        ) : item.type === "generated" ? (
          <Sparkles size={16} color="var(--ai)" />
        ) : (
          <SlideThumb title={item.title} brand="" chart={false} variant={item.type === "workproduct" ? "dark" : "light"} />
        )}
      </div>
      <div className="min-w-0 flex-1">
        <div className="text-[13px] font-medium">{item.title}</div>
        {item.subtitle && <div className="muted text-[11px]">{item.subtitle}</div>}
      </div>
      <button type="button" className="icon-btn borderless" aria-label={`Remove ${item.title} from my selection`} onClick={onRemove}>
        <X size={12} />
      </button>
    </div>
  );
}
